<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dismiss-button</name>
   <tag></tag>
   <elementGuidId>7ca3a9bc-b730-43fe-b2f7-98f4be6c83f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dismiss-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dismiss-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1d95de0a-5a80-4ca0-9d6e-0e1b994326b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dismiss-button</value>
      <webElementGuid>acc4d52d-fd25-43f5-be73-dbcad6d62ead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn skip</value>
      <webElementGuid>32b25524-057d-42fb-8ee3-b3283a9b91d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Close ad</value>
      <webElementGuid>f29bf3fa-ea1e-4614-8573-33ba5ece779c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5c2e0b09-9605-4d55-bb78-e7bb5a931524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>44d53de8-eaaa-4e0d-b3ad-62f06cffc49c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dismiss-button&quot;)</value>
      <webElementGuid>ec7fd166-74aa-4ded-9857-c9967df9ca35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/iframe_concat(id(, , aswift_1, , ))_aswift_1</value>
      <webElementGuid>7aacf83e-1d62-4bad-a263-f73c6c29a1e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='dismiss-button']</value>
      <webElementGuid>75774692-3567-4a1f-a3e5-b8d1647f2e37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='card']/div/div</value>
      <webElementGuid>ebedab57-295c-4b13-911a-667875944675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ad'])[1]/preceding::div[2]</value>
      <webElementGuid>653a855c-e8ff-4ce5-bf1f-56a309d30491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feedback on this ad'])[1]/preceding::div[7]</value>
      <webElementGuid>7a511a5c-133f-48cb-9c6f-77cfbab86dc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div</value>
      <webElementGuid>eacecd59-121f-4482-b150-95d86c729ab2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'dismiss-button']</value>
      <webElementGuid>c9996180-d30c-4454-8b88-a4791d78ad78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
